### ISSUE TITLE
[BUG] Can't reach folders in /Android/data

### ISSUE THREAD

**Issue by hiddense** [deltazefiro/Amarok-Hider#139]
The file browser doesn't show this folder as an option to browse due to scoped storage protections, despite Amarok having root access. 

If this can't be done without a custom file picker please consider please consider adding absolute paths as an option, such as `/sdcard/Android/data/folder`

Thanks.

**Comment by deltazefiro** [comment]
Sorry for the delayed response. 

> The file browser doesn't show this folder as an option to browse due to scoped storage protections, despite Amarok having root access.

Well it's by design. With root access, Amarok may hide, or in essence chmod, any directory including the system files. A careless mistake may brick the device. The system file picker can serve as an "idiot-proof" safeguard.

> If this can't be done without a custom file picker please consider please consider adding absolute paths as an option, such as /sdcard/Android/data/folder

It's already there! Just long-press the "Add hidden folder" button, and you’ll be able to manually enter the path :P

**Comment by deltazefiro** [comment]
Close as stale. Reopen if needed.
