### ISSUE TITLE
[FeatureRequest] Trigger hide by a shell command

### ISSUE THREAD

**Issue by LimerBoy** [deltazefiro/Amarok-Hider#152]
**Feature Description / 功能描述**
There is an application github.com/leohearts/AlternativeUnlockXposed that allows you to run commands when you enter a decoy password.

It would be great if you could trigger hiding applications by executing a shell command.

**Comment by deltazefiro** [comment]
Try this:
```
adb shell am broadcast -a deltazero.amarok.HIDE -n ${PKG_NAME}/.receivers.ActionReceiver
```
where `${PKG_NAME}` is the application ID of Amarok, `deltazero.amarok.foss` for the F-Droid version, and `deltazero.amarok` for the AppCenter version.

**Comment by LimerBoy** [comment]
> Try this:
> 
> ```
> adb shell am broadcast -a deltazero.amarok.HIDE -n ${PKG_NAME}/.receivers.ActionReceiver
> ```
> 
> where `${PKG_NAME}` is the application ID of Amarok, `deltazero.amarok.foss` for the F-Droid version, and `deltazero.amarok` for the AppCenter version.

tried commands wth both ids using root shell, but didn't worked

**Comment by deltazefiro** [comment]
> tried commands wth both ids using root shell, but didn't worked

Perhaps you are not using the latest version of Amarok? There was a change in intent API in v0.8.7a2. Please check if you are using v0.8.7a2 or newer.

**Comment by LimerBoy** [comment]
I'm using v0.8.7b1 (latest from fdroid)

**Comment by deltazefiro** [comment]
Could you please fill out this template to help reproduce it?

> tried commands wth both ids using root shell

I'm also interested in how you issued the adb command. Did you run the command on the device itself with a root shell? If so, how did you get the adb client?

---
**Describe the bug / 问题描述**
A clear and concise description of what the bug is.
请清晰地描述您遇到的异常。

**To Reproduce / 复现步骤**
Steps to reproduce the behavior / 复现异常的步骤:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior / 预期行为**
A clear and concise description of what you expected to happen.
描述您认为正常情况下应该发生什么。

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem.
（可选）问题复现时候的截图或录屏。

**Basic Information (please complete the following information) / 请填写以下信息:**
 - OS (ROM) / 系统: [e.g. MIUI 13]
 - Android Version / 安卓版本: [e.g. 12]
 - Amarok Version / Amarok版本: [e.g. v0.8.1b1-foss]

**Additional context / 其他信息**
Add any other context about the problem here.
在这里输入其他有关此异常的信息。

---

**Comment by LimerBoy** [comment]
Android 13
Amarok v0.8.7b1
App hide mode: Shizuku(sui) also tried with root mode.
Hides from Amarok UI but not from shell broadcast.

i sent both `am broadcast -a deltazero.amarok.HIDE -n deltazero.amarok.foss/.receivers.ActionReceiver` and `am broadcast -a deltazero.amarok.HIDE -n deltazero.amarok/.receivers.ActionReceiver`

from rooted Termux and [$HELL](https://f-droid.org/sq/packages/in.ac.dducollegedu.shell/) emulators, and received `Broadcast completed: result=0`

app is not disguised as calendar, i tested with both.

**Comment by deltazefiro** [comment]
Oh my. I omitted the package name in the command. It can only work on the AppCenter version XD
This one should work for the foss version.
```
adb shell am broadcast -a deltazero.amarok.HIDE -n deltazero.amarok.foss/deltazero.amarok.receivers.ActionReceiver
```

**Comment by LimerBoy** [comment]
Yes, it worked, thanks!
