### ISSUE TITLE
Question about fdroid and IzzyOnDroid versions

### ISSUE THREAD

**Issue by TorCzaf** [deltazefiro/Amarok-Hider#73]
Hi,  What is the difference between Amarok of F-droid and Amarok version of IzzyOnDroid?

And do both versions respect privacy and have no trackers or do they depend on third-party products or log data or such things that may be against privacy?
Thank You.

I don't know if anybody can see my issue or not, that is why I submitted it again.

**Comment by deltazefiro** [comment]
@TorCzaf :clap:   

> I don't know if anybody can see my issue or not, that is why I submitted it again.  

Yeah it's odd to find that the issue was opened 2 weeks ago, but I did not see it until today. Maybe it's a bug of GitHub.

>   Hi, What is the difference between Amarok of F-droid and Amarok version of IzzyOnDroid?

- IzzyOnDroid: Alpha pre-release channel.
- F-Droid: Stable channel, but due to the [issue](https://gitlab.com/fdroid/fdroiddata/-/commit/fe3d3f72de937fad396251d85c44bf4cebf90b43#note_1325098135), it has not been updated for a long time.

> And do both versions respect privacy and have no trackers or do they depend on third-party products or log data or such things that may be against privacy?

Yes.
